name: "Conventional Commits"
description: "Ensures that all commit messages are following the conventional-commits standard."
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: false
runs:
  using: 'node16'
  pre:
    - rm -rf dist/
    - echo "yes | npx tsx ./src/main.ts" > ./script.sh
    - chmod +x ./script.sh
    - ./script.sh
