name: "Conventional Commits"
description: "Ensures that all commit messages are following the conventional-commits standard."
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: false
runs:
  using: 'node16'
  steps:
    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Execute main script
      run: npx ts-node ./src/main.ts
      shell: bash
  pre:
    - rm -rf dist/
