name: Conventional Commits
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Shell Command
        run: |
          echo "This is a shell command."

      - name: Run Node.js Script
        uses: actions/setup-node@v2
        with:
          node-version: '16'
        run: |
          npm install
          node src/index.js
