name: Commits

on:
  pull_request:
  push:

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      name: Check commit messages
      run: |
        yes 2>/dev/null | npx tsx ./src/main.ts