name: Commits

on:
  pull_request:
  push:

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd ./src
          yes 2>/dev/null | npx tsx ./main.ts